# fly.toml app configuration file generated for pineapple-wallet-server on 2026-05-01T06:48:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pineapple-wallet-server'
primary_region = 'ams'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'ts-node prisma/seed.ts'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
